* List of Nyxt extensions

- [[https://github.com/kssytsrk/nx-freestance-handler][nx-freestance-handler]] ::
  nx-freestance-handler is a redirector from mainstream websites to their
  privacy-supporting mirrors for the Nyxt browser.  It is currently able to
  redirect from Youtube to Invidious, from Reddit to Teddit, from Instagram to
  Bibliogram, and from Twitter to Nitter.

- [[https://github.com/aartaka/nx-search-engines][nx-search-engines]] ::
  The aim of nx-search-engines is to get rid of black box world of search
  bookmarklets and search cookies by moving to the pretty land of lispy syntax
  and small helper functions generating search URIs.

- [[https://github.com/atlas-engineer/nx-ace][nx-ace]] ::
  nx-ace allows you to use the Ace editor within Nyxt. To use it, load it, and
  add =ace-mode= to your default modes for your =editor-buffer=.

- [[https://github.com/aartaka/nx-kaomoji.git][nx-kaomoji]] ::
  nx-kaomoji lets you paste Kaomojis to any input field with a dedicated
  command. Load it and run =kaomoji-fill= (or bind it to a key) in Nyxt.

- [[https://github.com/atlas-engineer/nx-fruit][nx-fruit]] ::
  nx-fruit lets you discover the fruit of the day!  A simple extension that you
  can use to test your Nyxt installation (i.e. can you load extensions).

- [[https://git.migalmoreno.com/nx-router][nx-router]] ::
  nx-router is a URL routing extension for Nyxt.  It provides a
  batteries-included abstraction around request resource handlers via =router=
  objects.

- [[https://git.migalmoreno.com/nx-tailor][nx-tailor]] ::
  nx-tailor is a wrapper around =nyxt/theme= that allows rule-based runtime theme
  switching.

- [[https://github.com/rolling-robot/nx-zotero][nx-zotero]] ::
  nx-zotero is a simple Zotero connector for Nyxt.

- [[https://github.com/aartaka/nx-dark-reader][nx-dark-reader]] ::
  nx-dark-reader is Nyxt (3.0+ only) integration with Dark Reader.

- [[https://gist.github.com/chaorace/98417a693ca73c51a8688ac09e61d2b0][nx-passt]] ::
  nx-passt is a =password-mode= interface that supports filename-based username.

- [[https://git.sr.ht/~ehrt74/nyxt-bitwarden][nx-bitwarden]] ::
  nx-bitwarden adds Bitwarden support for =password-mode=.
