* Next Developer Readme                                                 :TOC:
:PROPERTIES:
:TOC:      this
:END:
-  [[#developer-installation-with-guix][Developer Installation with Guix]]
  -  [[#run-from-source][Run from source]]
-  [[#standard-developer-installation][Standard Developer Installation]]
  -  [[#installing-sbcl][Installing SBCL]]
  -  [[#installing-quicklisp-optional][Installing Quicklisp (optional)]]
  -  [[#gtk-dependencies][GTK dependencies]]
    -  [[#lisp-dependencies][Lisp Dependencies]]
    -  [[#gnulinux-gtk-dependencies][GNU/Linux GTK dependencies]]
    -  [[#macos-specific-dependencies][macOS specific dependencies]]
  -  [[#qt-dependencies][Qt dependencies]]
    -  [[#lisp-dependencies][Lisp Dependencies]]
    -  [[#gnulinux-dependencies][GNU/Linux dependencies]]
    -  [[#macos-dependencies][macOS dependencies]]
  -  [[#fetch-the-source-code][Fetch the source code]]
  -  [[#compile][Compile]]
    -  [[#using-the-makefile][Using the Makefile]]
    -  [[#using-lisp][Using Lisp]]
  -  [[#run-from-source][Run from Source]]
  -  [[#update-local-lisp-libraries][Update local Lisp libraries]]
-  [[#help--community][Help & Community]]
  -  [[#learning-common-lisp][Learning Common Lisp]]
  -  [[#contribution][Contribution]]
  -  [[#irc-channel][IRC Channel]]

* Developer Installation with Guix
Install [[https://guix.gnu.org][Guix]] and follow the instructions in [[../build-scripts/guix.scm]].

** Run from source
If you are developing Next, you might prefer to run Next directly from
source so that you can skip the compilation step and iterate faster.

It is most convenient to clone the Next repository into
=~/common-lisp= (or [[https://www.common-lisp.net/project/asdf/asdf.html#Configuring-ASDF-to-find-your-systems][another directory where ASDF will find it]]). You
can then start Next using the command

#+begin_src sh
guix environment next -- sbcl --eval '(require :asdf)' --eval '(asdf:load-system "next/gtk")' --eval '(next:start)'
#+end_src

You can even start a Swank server immediately at startup using

#+begin_src sh
guix environment next -- sbcl --eval '(require :asdf)' --eval '(asdf:load-system "next/gtk")' --eval '(next:start-swank)' --eval '(next:start)'
#+end_src

* Standard Developer Installation
Next is written in Common Lisp. It can be built with any standard
Common Lisp implementation. Currently, only [[http://www.sbcl.org/][SBCL]] (≥ 1.4.2) support is
tested.

It is designed to be cross-platform, cross-engine compatible. Next is
available in both WebKit and WebEngine flavors. Support for graphics
and OS integration is provided via:

- macOS: GTK, Qt
- GNU/Linux: GTK, Qt

** Installing SBCL
You'll need SBCL ≥ 1.4.2 to compile Next.  (Previous versions require
an ASDF update.)

You can obtain SBCL from your package manager or by downloading it
directly from the SBCL repository.

To install SBCL from source, download SBCL:
[[http://www.sbcl.org/platform-table.html]]. Full installation
instructions can be found here: [[http://www.sbcl.org/getting.html]].

** Installing Quicklisp (optional)
Quicklisp is downloaded and installed automatically by the
Makefile. If you wish to install it manually- system-wide- the
official Quicklisp website can provide updated links to downloads, and
instructions: https://www.quicklisp.org.

To install Quicklisp:
- Download https://beta.quicklisp.org/quicklisp.lisp.
- Execute ~$LISP --load quicklisp.lisp~ to load Quicklisp. (Replace =$LISP= with
  =sbcl= or any supported Lisp compiler.)
- Evaluate in the REPL ~(quicklisp-quickstart:install)~ to install.
- Evaluate in the REPL ~(ql:add-to-init-file)~ to add Quicklisp to your Lisp init file.

** GTK dependencies
*** Lisp Dependencies
Next on GTK requires the latest version of the cl-webkit library.
Clone the cl-webkit repository into =~/common-lisp= or any directory
listed in ~asdf:*central-registry*~:

#+begin_src sh
git clone https://github.com/joachifm/cl-webkit ~/common-lisp/cl-webkit
#+end_src

*** GNU/Linux GTK dependencies
- WebKitGTK+ also known as webkit2gtk (make sure to use the most
  recent version for security reasons)
- glib-networking (for WebKitGTK+)
- gsettings-desktop-schemas (for WebKitGTK+)
- gstreamer, gst-plugins-* (for HTML audio/video)
- libfixposix
- xclip (for clipboard support)
- notify-osd (optional)
- enchant (for spellchecking)

- Debian-based distributions:
  #+begin_src sh
  sudo apt install sbcl libwebkit2gtk-4.0-dev glib-networking gsettings-desktop-schemas libfixposix-dev libgstreamer1.0-0 gir1.2-gst-plugins-base-1.0 xclip notify-osd enchant
  #+end_src

- Fedora:
  #+begin_src sh
  sudo dnf install sbcl webkit2gtk3-devel glib-networking gsettings-desktop-schemas libfixposix-devel gstreamer1-devel gstreamer1-plugins-base xclip enchant
  #+end_src

If your distribution does not install libraries in an [[https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard][FHS]]-expected location, you
have to let know your Lisp compiler where to find them.  To do so, add the
library directories to ~cffi:*foreign-library-directories*~ list.  For instance,
if you are running Guix you may want to expose =~/.guix-profile/lib= to the
compiler by adding the following snippet to =~/.sbclrc=:

#+begin_src lisp
(require "asdf")

(let ((guix-profile (format nil "~a/.guix-profile/lib/" (uiop:getenv "HOME"))))
  (when (and (probe-file guix-profile)
             (ignore-errors (asdf:load-system "cffi")))
    (push guix-profile
          (symbol-value (find-symbol (string '*foreign-library-directories*)
                                     (find-package 'cffi))))))
#+end_src

Install the WebKitGTK+ package of your distribution that provides
~libwebkit2gtk-4.0.so~ (the shared library for WebKitGTK+).

- For most Debian-based systems (including Ubuntu) this package is
  ~libwebkit2gtk-4.0-dev~.  /Debian Stable is not supported/.  Debian users are
  advised to use more up-to-date packages from Debian Testing at least.
- For Arch Linux this package is [[https://www.archlinux.org/packages/extra/x86_64/webkit2gtk/][webkit2gtk]].

#+begin_quote
A note of caution about installing WebKit via your package
manager: Your distribution supplied version of WebKit may not provide
up-to-date versions of WebKit including the latest security
patches. WebKitGTK+ tries to do the best job possible with maintaining
security patches upstream, but it is also up to the the
distribution provider to update their packages to take advantage of
these fixes.
#+end_quote

*** macOS specific dependencies
- GTK 3.24.12+
- WebKitGTK+
- XQuartz
- libfixposix

** Qt dependencies
*** Lisp Dependencies
Next on Qt requires the latest version of the cl-webengine library.
Clone the cl-webengine repository into =~/common-lisp= or any
directory listed in ~asdf:*central-registry*~:

#+begin_src sh
git clone git@github.com:atlas-engineer/cl-webengine.git ~/common-lisp/cl-webengine
#+end_src

Please follow the instructions in the cl-webengine repository for
details about how to install it on your system.

*** GNU/Linux dependencies
- Qt 5 (qtbase, qtwebchannel, qtdeclarative)
- Qt 5 WebEngine
- libfixposix
- xclip (for clipboard support)
- notify-osd (optional)
- enchant (for spellchecking)

*** macOS dependencies
- Qt 5.14.0+
- Qt WebEngine
- libfixposix

** Fetch the source code
Clone the Next repository into =~/common-lisp= or any directory listed in
~asdf:*central-registry*~:

#+begin_src sh
mkdir -p ~/common-lisp
git clone https://github.com/atlas-engineer/next ~/common-lisp/next
#+end_src

** Compile
*** Using the Makefile
The following command will build the Lisp core. On macOS this will produce an
application bundle which you can copy into your =/Applications= folder.

- GNU/Linux:
#+BEGIN_SRC sh
make all
#+END_SRC

- macOS:
#+BEGIN_SRC sh
make all
make app-bundle
#+END_SRC

Inside the Makefile you'll find many options you can specify. You can
specify to use your Lisp's init file, to use your global installation
of Quicklisp, or to automatically download and install a separate
Quicklisp installation for Next. Run ~make~ to display some
documentation. Please see the Makefile for more details.
*** Using Lisp
Start your Lisp and run the following commands:

#+NAME: compile
#+BEGIN_SRC lisp
(asdf:make :next/gtk-application)
#+END_SRC

your Lisp interpreter will have produced an executable in the
directory where the asd file is located. You can also compile the Qt
version like this:

#+NAME: compile
#+BEGIN_SRC lisp
(asdf:make :next/qt-application)
#+END_SRC

** Run from Source
If you are developing Next, you may prefer to run Next directly from
source so that you can skip the compilation step and iterate faster.

Make sure that Quicklisp is set up and up-to-date (see [[Update local Lisp
libraries]]) as explained in the Quicklisp section.

Then in a shell execute the following:

1. ~$LISP~ to create a new Lisp REPL (replace ~$LISP~ with ~sbcl~ or any
   supported Common Lisp compiler).
2. Execute ~(require :asdf)~ if ASDF is not already loaded.
3. Execute ~(asdf:load-asd "/full/path/to/next.asd")~ to load the Next
   system definition (you must use absolute pathnames).
4. Execute ~(ql:quickload :next/gtk)~ to load the Next system into your
   Lisp image.
5. Execute ~(next:start)~ to open your first Next window.

The above process is a bit cumbersome and you'll probably want a more
comfortable workflow from within your favourite editor.  For instance,
with Emacs and SLIME the process is:

1. =M-x slime RET=
2. =,load-system RET next RET=
3. =(next:start) RET=

See the [[https://lispcookbook.github.io/cl-cookbook/editor-support.html][Common Lisp Cookbook]] for a list of options for various editors.

** Update local Lisp libraries
If you use Quicklisp for Common Lisp library management outside the
context of Next, you may want to reuse your local distribution to
build Next.

To do so, invoke =make= with the following option:

#+begin_src sh
make NEXT_INTERNAL_QUICKLISP=false ...
#+end_src

In this case, you'll have to make sure the Quicklisp distribution is
up-to-date or else future versions of Next might fail to build.  In a
REPL:

#+begin_src lisp
(ql:update-dist "quicklisp")
#+end_src

If you use the internal Quicklisp distribution (i.e. with the default
=NEXT_INTERNAL_QUICKLISP=true=), the distribution is updated
automatically for you.

You will also need to manually update the [[Lisp specific dependencies]].

* Help & Community
There are several ways to ask for help from the community. The first
and easiest one is to simply open up an issue with whatever problem
you have. Feel free to open issues for any task, suggestion or
conversation you wish to have.

** Learning Common Lisp
There are a couple of resources out there to learn Common Lisp.

- [[http://www.gigamonkeys.com/book/][Practical Common Lisp]] is a popular book available for free.  It
  assumes you already know programming.  It gives a good coverage of
  the "core" of the language and goes to the point.

- The [[https://lispcookbook.github.io/cl-cookbook/][Common Lisp Cookbook]] is a modern, community maintained resource
  covering many aspects of Common Lisp programming and beyond, from
  editor setup to style.  The front page lists many other resources
  for learning, such as books (some available for free) and other web
  sites.  If you already know another Lisp/Scheme, the cookbook can
  serve as a good crash course.

** Contribution
To contribute, please find a task within [[file:CHANGELOG.org][CHANGELOG.org]] document that
has a TASK label affixed. Upon finding a task that you'd like to work
on, ideally, ensure that it is not already being worked on.

After you have found a TASK item that is available:

- make a fork of the repository,
- add your changes,
- make a pull request.

** IRC Channel
You can find Next on Freenode IRC at =#next-browser=.


# Local Variables:
# before-save-hook: org-make-toc
# End:
