;;;; cocoa.lisp --- cocoa helper functions & data

(in-package :interface)

(defun initialize ())
(defun start ())
(defun kill ())
(defun copy ())
(defun paste ())
(defun cut ())
(defun process-event ())
(defun set-visible-view ())
(defun delete-view ())
(defun make-web-view ())
(defun web-view-set-url ())
(defun web-view-set-url-loaded-callback ())
(defun web-view-get-url ())
(defun web-view-execute ())
(defun make-minibuffer ())
(defun minibuffer-show ())
(defun minibuffer-hide ())
(defun minibuffer-set-input ())
(defun minibuffer-get-input ())
(defun minibuffer-get-input-complete ())
(defun minibuffer-select-next ())
(defun minibuffer-select-previous ())
(defun minibuffer-set-completion-function ())
