;;;; cocoa.lisp --- cocoa helper functions & data

(in-package :interface)

(defun initialize ())
(defun start ())
(defun kill ())
(defun copy ())
(defun paste ())
(defun cut ())
(defun process-event ())
(defun set-visible-view (view))
(defun delete-view (view))
(defun make-web-view ())
(defun web-view-set-url (view url))
(defun web-view-set-url-loaded-callback (view function))
(defun web-view-get-url (view))
(defun web-view-execute (view script))
(defun make-minibuffer ())
(defun minibuffer-show ())
(defun minibuffer-hide ())
(defun minibuffer-set-input (input))
(defun minibuffer-get-input ())
(defun minibuffer-get-input-complete ())
(defun minibuffer-select-next ())
(defun minibuffer-select-previous ())
(defun minibuffer-set-completion-function (function))
