#+TITLE: NASDF

NASDF is an ASDF extension providing utilities to ease system setup, testing and
installation.

* Features

- Manage CL dependencies as Git submodules, ensuring fine control over their
  versions.
- Test suite helpers.
- Installation helpers such as handling of icons or desktop files.

See [[file:package.lisp]] for more details.

* Environment variables

NASDF exposes the following environment variables for convenience:

- =NASDF_SOURCE_PATH= :: See =nasdf:*dest-source-dir*=.
- =NASDF_SUBMODULES_DIR= :: See =nasdf:*submodules-directory*=.
- =NASDF_SUBMODULES_JOBS= :: See =nasdf:*submodules-jobs*=.
- =NASDF_USE_LOGICAL_PATHS= :: Allow non-expanded logical pathnames in system
  pathnames.
  This is particularly useful when shipping the source.
  Disable it if your tooling (e.g. SLIME) encounters issues to find the
  definition of symbols.
  See =asdf:nasdf-file=.
- =NASDF_TESTS_NO_NETWORK= :: Do no run tests that have the =:online= tag.
  See =nasdf:nasdf-test-system=.

All boolean environment variables try to be smart enough to understand what you
mean; for instance both =on= and =true= are valid values to enable the feature.
