;;;; search-buffer.lisp --- functions to enable searching within a webview

(in-package :next)

(defparen add-search-boxes (search-string)
  (defun insert (str index value)
    (+ (ps:chain str (substr 0 index)) value (ps:chain str (substr index))))
  (defun create-search-span (index)
    (ps:let* ((el (ps:chain document (create-element "span"))))
      (setf (ps:@ el class-name) "next-search-hint")
      (setf (ps:@ el style background) "rgba(255, 255, 255, 0.75)")
      (setf (ps:@ el style border) "1px solid red")
      (setf (ps:@ el style font-weight) "bold")
      (setf (ps:@ el style text-align) "center")
      (setf (ps:@ el text-content) "!")
      el))
  (let* ((regex-string (ps:lisp (concatenate 'string search-string "[A-Za-z]*")))
         (regex-flags "gi")
         (matcher (ps:new (-reg-exp regex-string regex-flags)))
         (body (ps:chain document body inner-h-t-m-l))
         (last-match t)
         (matches (loop while (setf last-match (ps:chain matcher (exec body)))
                     collect (ps:list (ps:chain last-match index) (+ 1 (ps:chain matcher last-index))))))
    (setf matches (ps:chain matches (reverse)))
    (loop for match in matches
       do (setf body (insert body (ps:elt match 0) (ps:chain (create-search-span 10) outer-h-t-m-l))))
    (setf (ps:chain document body inner-h-t-m-l) body)))
