* Analysis
Analysis is a library that provides facilities to help analyze and
understand data. Listed below are the classes:

** Document
The document class represents a document. After creating a document,
you can perform several operations on it, some examples:

+ term count: how many times does a term appear in a document?
+ term frequency: how many times does a term appear divided by the
  total number of words in the document?

** Document Collection
The document collection class represents a collection of documents. As
with a document, there are several operations available, some examples:

+ dictionary: which words appear in the document collection?
+ keywords: what are the important keywords in this document
  collection?

** Document Vertex
The document vertex class represents a document that is part of a
graph. The edges slot of the document vertex class is used to store
edges of that particular vertex. The keys in the edges slot hash table
are the actual vertexes, and the values are the edge weights.

** Document Cluster
The document cluster class represents a document that is part of a
graph which will be clustered. It extends the document-vertex class
and adds support for a cluster tag and a list of neighbors. These
slots are useful for clustering algorithms.
