(in-package :next)

(define-command about ()
  "Show the list of contributors."
  (let* ((buffer (make-buffer
                  :name "*About*"
                  :default-modes (cons 'help-mode
                                       (get-default 'buffer 'default-modes))))
         (contents (cl-markup:markup
                    (:h1 "Crowdfunding backers")
                    (:p "Thank you to all who have supported and made Next possible!")
                    (:h2 "2018-11 campaign: *NIX Support")
                    (:h3 "Digital Omnipresence")
                    (:ul
                     (:li "Alexander.Shendi")
                     (:li "Ashish SHUKLA")
                     (:li "Christopher Nascone")
                     (:li "dan.girsh")
                     (:li "Eric Monson")
                     (:li "Jack Randall")
                     (:li "James Anderson")
                     (:li "liweitian")
                     (:li "Marco Heisig")
                     (:li "Oluwafemi Agbabiaka")
                     (:li "pjb")
                     (:li "Robert Krahn")
                     (:li "Robert Uhl")
                     (:li "1 anonymous"))
                    (:h3 "Digital Magma")
                    (:ul
                     (:li "Daniel V")
                     (:li "Jason Hamilton")
                     (:li "Magnus Nyberg")
                     (:li "Marek Kochanowicz")
                     (:li "Rich Smith")
                     (:li "Robert Uhl")
                     (:li "simon")
                     (:li "slade")
                     (:li "Steve Last")
                     (:li "ulf.makestad")
                     (:li "1 anonymous"))
                    (:h3 "Digital Immortality")
                    (:ul
                     (:li "Alexey Abramov")
                     (:li "Are Jensen")
                     (:li "Joseph Mingrone")
                     (:li "Nikita Poliakov")
                     (:li "pjb")
                     (:li "Sainath Adapa")
                     (:li "Spencer Heywood")
                     (:li "Sungjin Chun")
                     (:li "Tom Delord")
                     (:li "2 anonymous"))
                    (:h3 "Others")
                    (:ul
                     (:li "Nicholas Zivkovic")
                     (:li "Pierre Neidhardt")
                     (:li "Simon Zugmeyer")
                     (:li "vindarel")
                     (:li "5 anonymous"))))
         (insert-content (ps:ps (setf (ps:@ document body |innerHTML|)
                                      (ps:lisp contents)))))
    (rpc-buffer-evaluate-javascript *interface* buffer insert-content)
    (set-active-buffer *interface* buffer)))
